## Utilizing NumPy Functions 01/02

In [2]:
import numpy as np

# Create an array of size 10 filled with 0
z = np.zeros(10)
z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [3]:
# Set fifth value to 1 from above array
z[4] = 1
z

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

In [4]:
# Create an array with values ranging from 10 to 49
r = np.random.randint(low=10, high=50, size=40)
r

array([13, 41, 49, 38, 48, 29, 24, 11, 30, 28, 48, 23, 21, 27, 19, 39, 48,
       26, 47, 29, 26, 34, 23, 16, 36, 30, 12, 23, 26, 11, 38, 33, 31, 49,
       44, 41, 22, 31, 25, 35])

In [6]:
# Create a 5 * 5 matrix with values ranging from 0 to 24
mat = np.random.randint(25, size=(5, 5))
mat

array([[12,  1,  7, 10, 13],
       [21, 10,  7,  3,  3],
       [24,  4,  2, 18, 18],
       [16, 14,  8,  0, 14],
       [17, 20,  7, 19,  0]])

In [7]:
# Create a 5 * 5 identity matrix
i = np.eye(5)
i

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

## Utilizing NumPy Functions 02/02

In [8]:
print('Create an 5*5 array with random values and find the minimum and maximum value')
print()
d=np.random.rand(5,5)
print(d)
print('Minimum Value: ', d.min())
print('Maximum Value: ',d.max())

(6) Create an 5*5 array with random values and find the minimum and maximum value

[[ 0.97649958  0.22264124  0.88857068  0.58187043  0.86514576]
 [ 0.10006956  0.37317164  0.65920511  0.07532205  0.72302009]
 [ 0.50739514  0.14257119  0.57136539  0.88692884  0.47562574]
 [ 0.95138162  0.10502486  0.26996422  0.27660991  0.48759894]
 [ 0.48923764  0.70757402  0.737395    0.00911762  0.89835385]]
Minimum Value:  0.0091176232289
Maximum Value:  0.976499576836


In [9]:
print('Multiply a 4*3 matrix by a 3*2 matrix')
print()
e=np.ones((4,3))
f=np.random.rand(3,2)
g=e.dot(f)
print(g)

(7) Multiply a 4*3 matrix by a 3*2 matrix

[[ 0.91895878  1.56633367]
 [ 0.91895878  1.56633367]
 [ 0.91895878  1.56633367]
 [ 0.91895878  1.56633367]]


In [10]:
print('Transpose above matrix')
print()
print(g.transpose())
print()

Transpose above matrix

[[ 0.91895878  0.91895878  0.91895878  0.91895878]
 [ 1.56633367  1.56633367  1.56633367  1.56633367]]



In [11]:
print('Create two matrices ranging from 0 to 24 and 25 to 49')
print()
h=np.array(range(0,25))
i=np.array(range(25,50))
print('Add: ',h+i)
print('Subtract: ',h-i)

Create two matrices ranging from 0 to 24 and 25 to 49

Add:  [25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73]
Subtract:  [-25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25 -25
 -25 -25 -25 -25 -25 -25 -25]


## Utilizing "pandans" Module 01/04

In [12]:
import pandas as pd
import numpy as np
exam_data = {'name':['Anatasia', 'Catherine','Cahil', 'James', 'Emily', 'Michael',
                     'Monica','Laura', 'Kevin', 'Jordan'],
           'score' : [13, 9.5, 16.5, np.nan, 11, 20, 17, np.nan, 8.5, 19],
            'attempts' : [1,3,3,2,2,3,2,3,2,1],
            'qualify' : ['yes','no','yes','no','no','yes','yes','no','no','yes']
            }
labels = ['a','b','c','d','e','f','g','h','i','j']
df = pd.DataFrame(exam_data, index = labels)
df

attempts       name qualify  score
a         1   Anatasia     yes   13.0
b         3  Catherine      no    9.5
c         3      Cahil     yes   16.5
d         2      James      no    NaN
e         2      Emily      no   11.0
f         3    Michael     yes   20.0
g         2     Monica     yes   17.0
h         3      Laura      no    NaN
i         2      Kevin      no    8.5
j         1     Jordan     yes   19.0

In [13]:
# Select the 'name' and 'score' columns from the above DataFrame
df[['name','score']]

name  score
a   Anatasia   13.0
b  Catherine    9.5
c      Cahil   16.5
d      James    NaN
e      Emily   11.0
f    Michael   20.0
g     Monica   17.0
h      Laura    NaN
i      Kevin    8.5
j     Jordan   19.0

In [14]:
# Select First Three rows of the DataFrame
df.iloc[:3]

attempts       name qualify  score
a         1   Anatasia     yes   13.0
b         3  Catherine      no    9.5
c         3      Cahil     yes   16.5

In [23]:
# Select 'name' and 'score' columns in rows 1,2,5,6 from the following data frame
df[['name','score']].iloc[[1,2,5,6],:]

name  score
b  Catherine    9.5
c      Cahil   16.5
f    Michael   20.0
g     Monica   17.0

In [24]:
# Select all rows whose attemps is larger than 2
df[df['attempts']>2]

attempts       name qualify  score
b         3  Catherine      no    9.5
c         3      Cahil     yes   16.5
f         3    Michael     yes   20.0
h         3      Laura      no    NaN

## Utilizing "pandans" Module 02/04

In [26]:
# Select the rows where the score is missing(NaN)
df[df.isnull().sum(axis=1) > 0 ]

attempts   name qualify  score
d         2  James      no    NaN
h         3  Laura      no    NaN

In [27]:
# Select the rows where number of attempts in the examination is less than 2 and score greater than 15
df[(df['attempts']<2)&(df['score']>15)]

attempts    name qualify  score
j         1  Jordan     yes   19.0

In [29]:
# Calculate the sum of the examination attemps
df['attempts'].sum()

22

In [30]:
# Calculate the mean of the score
df['score'].mean()

14.3125

## Utilizing "pandans" Module 03/04

In [9]:
import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Catherine', 'Cahill', 'James', 'Emily', 'Michael','Monica', 'Laura', 'Kevin', 'Jordan'],
             'score': [13, 9.5, 16.5, np.nan, 11, 20, 17, np.nan, 8.5, 19],
             'attempts': [1,3,3,2,2,3,2,3,2,1],
             'qualify': ['yes',' no', 'yes', 'no','no','yes','yes','no','no','yes']
            }
labels = ['a','b', 'c','d','e','f','g','h','i','j']
df = pd.DataFrame(exam_data,index=labels)


In [10]:
# Append a new row 'k'
df.loc['k'] = [2,"Saya","yes", 17.5]

In [11]:
df

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
d         2      James      no    NaN
e         2      Emily      no   11.0
f         3    Michael     yes   20.0
g         2     Monica     yes   17.0
h         3      Laura      no    NaN
i         2      Kevin      no    8.5
j         1     Jordan     yes   19.0
k         2       Saya     yes   17.5

In [12]:
# Delete  the new row and return the original data frame from above problem
df.drop('k', axis=0)

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
d         2      James      no    NaN
e         2      Emily      no   11.0
f         3    Michael     yes   20.0
g         2     Monica     yes   17.0
h         3      Laura      no    NaN
i         2      Kevin      no    8.5
j         1     Jordan     yes   19.0

In [13]:
# Delete 'attempts' column
df.drop('attempts', axis=1)

name qualify  score
a  Anastasia     yes   13.0
b  Catherine      no    9.5
c     Cahill     yes   16.5
d      James      no    NaN
e      Emily      no   11.0
f    Michael     yes   20.0
g     Monica     yes   17.0
h      Laura      no    NaN
i      Kevin      no    8.5
j     Jordan     yes   19.0
k       Saya     yes   17.5

In [14]:
# Get the sum of score group by 'attempts'
df.groupby('attempts').sum()

score
attempts       
1          32.0
2          54.0
3          46.0

## Utilizing "pandans" Module 04/04

In [16]:
import pandas as pd
import numpy as np

exam_data = {'name': ['Anastasia', 'Catherine', 'Cahill', 'James', 'Emily', 'Michael','Monica', 'Laura', 'Kevin', 'Jordan'],
             'score': [13, 9.5, 16.5, np.nan, 11, 20, 17, np.nan, 8.5, 19],
             'attempts': [1,3,3,2,2,3,2,3,2,1],
             'qualify': ['yes',' no', 'yes', 'no','no','yes','yes','no','no','yes']
            }
labels = ['a','b', 'c','d','e','f','g','h','i','j']
df = pd.DataFrame(exam_data,index=labels)

df

attempts       name qualify  score
a         1  Anastasia     yes   13.0
b         3  Catherine      no    9.5
c         3     Cahill     yes   16.5
d         2      James      no    NaN
e         2      Emily      no   11.0
f         3    Michael     yes   20.0
g         2     Monica     yes   17.0
h         3      Laura      no    NaN
i         2      Kevin      no    8.5
j         1     Jordan     yes   19.0

In [17]:
exam2_data = {'name': ['Anastasia', 'Catherine', 'Ronaldo', 'James', 'Messi', 'Michael','Monica', 'Laura', 'Kalssen', 'Jonas'],
             'score2': [11, 20, 16.5, np.nan, 10, 15, 20, np.nan, 8, 8]
              }
labels2 = ['a','b', 'c','d','e','f','g','h','i','j']
df2 = pd.DataFrame(exam2_data,index=labels2)
# Do inner join above df and below df2
merged_df = df.merge(df2, how="inner", left_index=True, right_index=True)
merged_df


attempts     name_x qualify  score     name_y  score2
a         1  Anastasia     yes   13.0  Anastasia    11.0
b         3  Catherine      no    9.5  Catherine    20.0
c         3     Cahill     yes   16.5    Ronaldo    16.5
d         2      James      no    NaN      James     NaN
e         2      Emily      no   11.0      Messi    10.0
f         3    Michael     yes   20.0    Michael    15.0
g         2     Monica     yes   17.0     Monica    20.0
h         3      Laura      no    NaN      Laura     NaN
i         2      Kevin      no    8.5    Kalssen     8.0
j         1     Jordan     yes   19.0      Jonas     8.0